### ISSUE TITLE
Umbra: OOM on loading data

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickBench#543]
It can't load data on a machine with 16 GB of memory or less.

**Comment by rschu1ze** [comment]
@toschmidt @lukasvogel

**Comment by ChrisWint** [comment]
Thanks for reporting, we'll look into it

**Comment by ChrisWint** [comment]
Created an issue for that in our Bugtracker to keep track of it: https://github.com/cedardb/issues/issues/20

**Comment by ChrisWint** [comment]
@alexey-milovidov @rschu1ze This should be fixed for CedarDB in the latest release

**Comment by rschu1ze** [comment]
For CedarDB, it's fixed indeed (I tested on c6a.2xlarge).

For Umbra, the issue persists. I tried on a `latest` machine (the submission previously used 25.7, [fix](https://github.com/ClickHouse/ClickBench/pull/696))

```
15466496K ........ ........ ........ ........ 97% 98.3M 4s
15499264K ........ ........ ........ ........ 97% 92.8M 4s
15532032K ........ ........ ........ ........ 97% 87.0M 4s
15564800K ........ ........ ........ ........ 97% 88.6M 3s
15597568K ........ ........ ........ ........ 98%  122M 3s
15630336K ........ ........ ........ ........ 98% 95.2M 3s
15663104K ........ ........ ........ ........ 98% 95.8M 2s
15695872K ........ ........ ........ ........ 98% 95.2M 2s
15728640K ........ ........ ........ ........ 99% 95.6M 2s
15761408K ........ ........ ........ ........ 99% 91.6M 1s
15794176K ........ ........ ........ ........ 99% 92.0M 1s
15826944K ........ ........ ........ ........ 99% 91.8M 1s
15859712K ........ ........ ........ ........ 99% 80.6M 0s
15892480K ........ ........ .......          100%  122M=2m43s

2025-11-15 17:36:58 (95.4 MB/s) - ‘hits.tsv.gz’ saved [16298506510/16298506510]

Unable to find image 'umbradb/umbra:latest' locally
latest: Pulling from umbradb/umbra
c62190a9ab61: Pull complete
61f0b5ee5e6b: Pull complete
d92623c9d7fc: Pull complete
83809684defe: Pull complete
02dbafc72a99: Pull complete
986972f530da: Pull complete
72680096bf27: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:1a0fd9e410e3ee9d9b5ec7a00126304901135bfb9469dca16f9d0b07268693b0
Status: Downloaded newer image for umbradb/umbra:latest
959db519fc36cc8bd81b88cd5ed4ea9fc43decb51573b21ca152e9dda7785ba9
CREATE TABLE
psql:create.sql:109: ERROR:  unable to allocate memory
Load time: 210
3
959db519fc36
psql: error: connection to server at "127.0.0.1", port 5432 failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
 ?column?
----------
 Ok
(1 row)
```

Perhaps @toschmidt likes to take a look?
